import { BlocksMetadata, categoryIds } from "./declarations";

export const blocksMetadata: BlocksMetadata[] = [
  {
    id: "form-layout-01",
    category: categoryIds.FormLayout,
    name: "Form with Workspace Fields",
    iframeHeight: "585px",
    type: "file",
  },
  {
    id: "form-layout-02",
    category: categoryIds.FormLayout,
    name: "Form with Side Labels",
    iframeHeight: "920px",
    type: "file",
  },
  {
    id: "form-layout-03",
    category: categoryIds.FormLayout,
    name: "Form with Checkbox Settings",
    iframeHeight: "1060px",
    type: "file",
  },
  {
    id: "form-layout-04",
    category: categoryIds.FormLayout,
    name: "Form with Package Selection",
    iframeHeight: "800px",
    type: "file",
  },
  {
    id: "form-layout-05",
    category: categoryIds.FormLayout,
    name: "Form with Plan Selection",
    iframeHeight: "1240px",
    type: "file",
  },

  {
    id: "login-01",
    category: categoryIds.Login,
    name: "Login with Email and Google",
    iframeHeight: "400px",
    type: "file",
  },
  {
    id: "login-02",
    category: categoryIds.Login,
    name: "Login with Email, Password and Google",
    iframeHeight: "500px",
    type: "file",
  },
  {
    id: "login-03",
    category: categoryIds.Login,
    name: "Login with Email and Password",
    iframeHeight: "420px",
    type: "file",
  },
  {
    id: "login-04",
    category: categoryIds.Login,
    name: "Login with Social Buttons",
    iframeHeight: "620px",
    type: "file",
  },
  {
    id: "login-05",
    category: categoryIds.Login,
    name: "Login Card Signup Form",
    iframeHeight: "750px",
    type: "file",
  },
  {
    id: "login-06",
    category: categoryIds.Login,
    name: "Login with Magic Link and SSO",
    iframeHeight: "700px",
    type: "file",
  },
  {
    id: "login-07",
    category: categoryIds.Login,
    name: "Login Full Page with Icons",
    iframeHeight: "700px",
    type: "file",
  },
  {
    id: "login-08",
    category: categoryIds.Login,
    name: "Login with SSO",
    iframeHeight: "680px",
    type: "file",
  },
  {
    id: "login-09",
    category: categoryIds.Login,
    name: "Login Signup with Role Selection",
    iframeHeight: "880px",
    type: "file",
  },

  {
    id: "grid-list-01",
    category: categoryIds.GridList,
    name: "Grid List with Dropdown",
    iframeHeight: "200px",
    type: "file",
  },
  {
    id: "grid-list-02",
    category: categoryIds.GridList,
    name: "Grid List with Links",
    iframeHeight: "250px",
    type: "file",
  },
  {
    id: "grid-list-03",
    category: categoryIds.GridList,
    name: "Grid List with Icons",
    iframeHeight: "500px",
    type: "file",
  },
];
