import { IllustrationsMetadata, illustrationCategoryIds } from "./illustrations/declarations";

export const illustrationsMetadata: IllustrationsMetadata[] = [
  { id: "accordion-illustration", category: illustrationCategoryIds.Accordion, name: "Accordion Illustration", type: "file" },
  { id: "alert-illustration", category: illustrationCategoryIds.Alert, name: "Alert Illustration", type: "file" },
  { id: "alert-dialog-illustration", category: illustrationCategoryIds.AlertDialog, name: "Alert Dialog Illustration", type: "file" },
  { id: "autocomplete-illustration", category: illustrationCategoryIds.Autocomplete, name: "Autocomplete Illustration", type: "file" },
  { id: "avatar-illustration", category: illustrationCategoryIds.Avatar, name: "Avatar Illustration", type: "file" },
  { id: "badge-illustration", category: illustrationCategoryIds.Badge, name: "Badge Illustration", type: "file" },
  { id: "breadcrumb-illustration", category: illustrationCategoryIds.Breadcrumb, name: "Breadcrumb Illustration", type: "file" },
  { id: "button-illustration", category: illustrationCategoryIds.Button, name: "Button Illustration", type: "file" },
  { id: "calendar-illustration", category: illustrationCategoryIds.Calendar, name: "Calendar Illustration", type: "file" },
  { id: "card-illustration", category: illustrationCategoryIds.Card, name: "Card Illustration", type: "file" },
  { id: "checkbox-illustration", category: illustrationCategoryIds.Checkbox, name: "Checkbox Illustration", type: "file" },
  { id: "checkbox-group-illustration", category: illustrationCategoryIds.CheckboxGroup, name: "Checkbox Group Illustration", type: "file" },
  { id: "collapsible-illustration", category: illustrationCategoryIds.Collapsible, name: "Collapsible Illustration", type: "file" },
  { id: "combobox-illustration", category: illustrationCategoryIds.Combobox, name: "Combobox Illustration", type: "file" },
  { id: "command-illustration", category: illustrationCategoryIds.Command, name: "Command Illustration", type: "file" },
  { id: "date-picker-illustration", category: illustrationCategoryIds.DatePicker, name: "Date Picker Illustration", type: "file" },
  { id: "dialog-illustration", category: illustrationCategoryIds.Dialog, name: "Dialog Illustration", type: "file" },
  { id: "drawer-illustration", category: illustrationCategoryIds.Drawer, name: "Drawer Illustration", type: "file" },
  { id: "empty-illustration", category: illustrationCategoryIds.Empty, name: "Empty Illustration", type: "file" },
  { id: "field-illustration", category: illustrationCategoryIds.Field, name: "Field Illustration", type: "file" },
  { id: "fieldset-illustration", category: illustrationCategoryIds.Fieldset, name: "Fieldset Illustration", type: "file" },
  { id: "footer-illustration", category: illustrationCategoryIds.Footer, name: "Footer Illustration", type: "file" },
  { id: "form-illustration", category: illustrationCategoryIds.Form, name: "Form Illustration", type: "file" },
  { id: "frame-illustration", category: illustrationCategoryIds.Frame, name: "Frame Illustration", type: "file" },
  { id: "group-illustration", category: illustrationCategoryIds.Group, name: "Group Illustration", type: "file" },
  { id: "input-illustration", category: illustrationCategoryIds.Input, name: "Input Illustration", type: "file" },
  { id: "input-group-illustration", category: illustrationCategoryIds.InputGroup, name: "Input Group Illustration", type: "file" },
  { id: "input-otp-illustration", category: illustrationCategoryIds.InputOtp, name: "Input OTP Illustration", type: "file" },
  { id: "kbd-illustration", category: illustrationCategoryIds.Kbd, name: "Keyboard Illustration", type: "file" },
  { id: "label-illustration", category: illustrationCategoryIds.Label, name: "Label Illustration", type: "file" },
  { id: "menu-illustration", category: illustrationCategoryIds.Menu, name: "Menu Illustration", type: "file" },
  { id: "meter-illustration", category: illustrationCategoryIds.Meter, name: "Meter Illustration", type: "file" },
  { id: "number-field-illustration", category: illustrationCategoryIds.NumberField, name: "Number Field Illustration", type: "file" },
  { id: "on-hover-illustration", category: illustrationCategoryIds.OnHover, name: "On Hover Animation Illustration", type: "file", hasAnimation: true },
  { id: "pagination-illustration", category: illustrationCategoryIds.Pagination, name: "Pagination Illustration", type: "file" },
  { id: "popover-illustration", category: illustrationCategoryIds.Popover, name: "Popover Illustration", type: "file" },
  { id: "preview-card-illustration", category: illustrationCategoryIds.PreviewCard, name: "Preview Card Illustration", type: "file" },
  { id: "progress-illustration", category: illustrationCategoryIds.Progress, name: "Progress Illustration", type: "file" },
  { id: "radio-group-illustration", category: illustrationCategoryIds.RadioGroup, name: "Radio Group Illustration", type: "file" },
  { id: "scroll-area-illustration", category: illustrationCategoryIds.ScrollArea, name: "Scroll Area Illustration", type: "file" },
  { id: "select-illustration", category: illustrationCategoryIds.Select, name: "Select Illustration", type: "file" },
  { id: "separator-illustration", category: illustrationCategoryIds.Separator, name: "Separator Illustration", type: "file" },
  { id: "sheet-illustration", category: illustrationCategoryIds.Sheet, name: "Sheet Illustration", type: "file" },
  { id: "skeleton-illustration", category: illustrationCategoryIds.Skeleton, name: "Skeleton Illustration", type: "file" },
  { id: "slider-illustration", category: illustrationCategoryIds.Slider, name: "Slider Illustration", type: "file" },
  { id: "spinner-illustration", category: illustrationCategoryIds.Spinner, name: "Spinner Illustration", type: "file" },
  { id: "switch-illustration", category: illustrationCategoryIds.Switch, name: "Switch Illustration", type: "file" },
  { id: "table-illustration", category: illustrationCategoryIds.Table, name: "Table Illustration", type: "file" },
  { id: "tabs-illustration", category: illustrationCategoryIds.Tabs, name: "Tabs Illustration", type: "file" },
  { id: "textarea-illustration", category: illustrationCategoryIds.Textarea, name: "Textarea Illustration", type: "file" },
  { id: "toast-illustration", category: illustrationCategoryIds.Toast, name: "Toast Illustration", type: "file" },
  { id: "toggle-illustration", category: illustrationCategoryIds.Toggle, name: "Toggle Illustration", type: "file" },
  { id: "toggle-group-illustration", category: illustrationCategoryIds.ToggleGroup, name: "Toggle Group Illustration", type: "file" },
  { id: "toolbar-illustration", category: illustrationCategoryIds.Toolbar, name: "Toolbar Illustration", type: "file" },
  { id: "tooltip-illustration", category: illustrationCategoryIds.Tooltip, name: "Tooltip Illustration", type: "file" },
];
