export type IllustrationsMetadata = {
  id: string;
  category: string;
  name: string;
  type: "file" | "directory";
  iframeHeight?: string;
  hasAnimation?: boolean;
};

export const illustrationCategoryIds = {
  Accordion: "accordion",
  Alert: "alert",
  AlertDialog: "alert-dialog",
  Autocomplete: "autocomplete",
  Avatar: "avatar",
  Badge: "badge",
  Breadcrumb: "breadcrumb",
  Button: "button",
  Calendar: "calendar",
  Card: "card",
  Checkbox: "checkbox",
  CheckboxGroup: "checkbox-group",
  Collapsible: "collapsible",
  Combobox: "combobox",
  Command: "command",
  DatePicker: "date-picker",
  Dialog: "dialog",
  Drawer: "drawer",
  Empty: "empty",
  Field: "field",
  Fieldset: "fieldset",
  Footer: "footer",
  Form: "form",
  Frame: "frame",
  Group: "group",
  Input: "input",
  InputGroup: "input-group",
  InputOtp: "input-otp",
  Kbd: "kbd",
  Label: "label",
  Menu: "menu",
  Meter: "meter",
  NumberField: "number-field",
  OnHover: "on-hover",
  Pagination: "pagination",
  Popover: "popover",
  PreviewCard: "preview-card",
  Progress: "progress",
  RadioGroup: "radio-group",
  ScrollArea: "scroll-area",
  Select: "select",
  Separator: "separator",
  Sheet: "sheet",
  Skeleton: "skeleton",
  Slider: "slider",
  Spinner: "spinner",
  Switch: "switch",
  Table: "table",
  Tabs: "tabs",
  Textarea: "textarea",
  Toast: "toast",
  Toggle: "toggle",
  ToggleGroup: "toggle-group",
  Toolbar: "toolbar",
  Tooltip: "tooltip",
  Animation: "animation",
} as const;
